/**
 * TOURNAMENT & LEAGUE DATA
 * ========================
 * This is the "database" for the site: a plain JavaScript array so the page
 * works by just double-clicking index.html (no server/build step needed).
 * Despite the variable name, TOURNAMENTS holds both one-off tournaments and
 * ongoing leagues. See `activityType` below.
 *
 * Every entry below is REAL, verified at the time this site was built. There
 * is no single feed that lists every US badminton tournament or league, so
 * these were gathered from several different kinds of sources on purpose:
 * USA Badminton's sanctioned circuit, TournamentSoftware's own national
 * search (both tournaments and leagues), independent club websites, Facebook
 * event/club pages, and university recreation calendars. See README.md for
 * exactly where each type was found and how to add more.
 *
 * HOW TO ADD AN ENTRY
 * ------------------------
 * Copy an existing object below, give it a unique "id", and fill in the fields.
 * See README.md for a full field-by-field guide, including how to look up
 * "lat"/"lng" for an address (needed for the "distance from me" sort).
 *
 * activityType: "league" marks an ongoing/recurring league (shown with a
 * "League" badge and a square map marker instead of a round one). Omit the
 * field entirely (as all the original entries do) for a one-off tournament;
 * that's the default, so existing entries didn't need updating.
 *
 * registrationDeadline: use "YYYY-MM-DDTHH:mm:ss" in the tournament's LOCAL
 * time, or null if unknown/not yet announced (it will sort to the bottom and
 * show "TBD"). For a league this is the season sign-up deadline, not a
 * per-match date.
 *
 * entries / entriesUpdated: how many players have signed up so far, plus the
 * date that number was read. Only TournamentSoftware publishes this, on the
 * tournament overview page next to the "Events" count, so most non-TS entries
 * simply leave both fields off. Leaving them off is meaningful: the site sorts
 * events with no count to the bottom of the "Number of entries" sort instead
 * of treating them as zero. A real 0 (registration open, nobody entered yet)
 * should be stored as 0, not omitted. A couple of BWF-sanctioned events sit
 * behind a login on bwf.tournamentsoftware.com and have no public count, so
 * they stay unset too. The daily scheduled task refreshes these numbers.
 */

const TOURNAMENTS = [
  // ---------------------------------------------------------------------
  // USA Badminton sanctioned tournaments (verified via usabadminton.org /
  // TournamentSoftware)
  // ---------------------------------------------------------------------
  {
    id: "usab-nationals-2026",
    name: "2026 YONEX U.S. Adult National Championships",
    level: "National Championship",
    venue: "Peak Sports",
    city: "Morrisville",
    state: "NC",
    address: "Peak Sports, Morrisville, NC",
    lat: 35.8235,
    lng: -78.8256,
    startDate: "2026-12-19",
    endDate: "2026-12-22",
    registrationDeadline: null,
    deadlineNote: "Not yet announced; check the official prospectus",
    prizeMoney: null,
    prizeNote: "Amateur national championship; no cash prize",
    sourcePlatform: "USA Badminton",
    sourceUrl: "https://usabadminton.org/athletes/adults/adult-tournament-schedule/",
    description: "USA Badminton's premier annual adult national championship, open to eligible USAB members."
  },
  {
    id: "socal-orc-2026",
    name: "2026 YONEX Arena SoCal Open Regional Championships",
    level: "Regional Championship",
    venue: "Arena Badminton & Sports Club",
    city: "Pomona",
    state: "CA",
    address: "Arena Badminton & Sports Club, Pomona, CA",
    lat: 34.0551,
    lng: -117.75,
    startDate: "2026-01-17",
    endDate: "2026-01-19",
    registrationDeadline: "2026-01-08T11:59:00",
    deadlineNote: "11:59 AM PST",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/tournament/239635E4-C300-4F6A-A364-7062F0430F30",
    description: "USA Badminton sanctioned Open Regional Championship for the Southern California region."
  },
  {
    id: "cba-midwest-olc-2026",
    name: "2025-2026 USA Badminton Open Local Championships: Midwest",
    level: "Local Championship",
    venue: "Chicago Badminton Academy",
    city: "Chicago",
    state: "IL",
    address: "Chicago Badminton Academy, Chicago, IL",
    lat: 41.8781,
    lng: -87.6298,
    startDate: "2026-01-10",
    endDate: "2026-01-11",
    registrationDeadline: "2026-01-01T11:59:00",
    deadlineNote: "11:59 AM PST",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/tournament/58FD9D91-2FE9-4613-9E59-6D56ADE8BF5B",
    description: "USA Badminton sanctioned Open Local Championship for the Midwest region."
  },
  {
    id: "bintang-norcal-olc-2026",
    name: "2026 Bintang NorCal Open Local Championship",
    level: "Local Championship",
    venue: "Bintang Badminton",
    city: "Fremont",
    state: "CA",
    address: "Bintang Badminton, Fremont, CA",
    lat: 37.5485,
    lng: -121.9886,
    startDate: "2026-03-13",
    endDate: "2026-03-15",
    registrationDeadline: "2026-02-26T11:59:00",
    deadlineNote: "11:59 AM PST",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/tournament/5779DD58-5F08-4D64-A092-B41478B07A0A",
    description: "USA Badminton sanctioned Open Local Championship for the Northern California region."
  },
  {
    id: "schafer-south-olc-2026",
    name: "2026 Schafer South Open Local Championship",
    level: "Local Championship",
    venue: "Schafer Badminton Academy",
    city: "Katy",
    state: "TX",
    address: "Schafer Badminton Academy, Katy, TX",
    lat: 29.7858,
    lng: -95.8244,
    startDate: "2026-04-18",
    endDate: "2026-04-19",
    registrationDeadline: "2026-04-02T11:59:00",
    deadlineNote: "11:59 AM PST",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/tournament/138de723-8d99-44de-a898-13492ad3f717",
    description: "USA Badminton sanctioned Open Local Championship for the South region, near Houston."
  },
  {
    id: "northwest-orc-2026",
    name: "2026 YONEX Northwest Open Regional Championships",
    level: "Regional Championship",
    venue: "Bellevue Badminton Club",
    city: "Tukwila",
    state: "WA",
    address: "Bellevue Badminton Club, Tukwila, WA",
    lat: 47.4779,
    lng: -122.261,
    startDate: "2026-09-05",
    endDate: "2026-09-07",
    registrationDeadline: "2026-08-13T11:59:00",
    deadlineNote: "11:59 AM PDT",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/tournament/8DD88094-231A-4215-9B91-A32C52625D01",
    description: "USA Badminton sanctioned Open Regional Championship for the Pacific Northwest region."
  },
  {
    id: "dave-freeman-open-2026",
    name: "2026 YONEX Dave Freeman Open",
    level: "Open Tournament",
    venue: "San Diego Badminton Club",
    city: "San Diego",
    state: "CA",
    address: "San Diego Badminton Club, San Diego, CA",
    lat: 32.7157,
    lng: -117.1611,
    startDate: "2026-02-20",
    endDate: "2026-02-22",
    registrationDeadline: null,
    deadlineNote: "Not listed publicly; check the official prospectus",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "USA Badminton",
    sourceUrl: "https://usabadminton.org/2026-dave-freeman-open-and-junior-olc-prospectuses-released/",
    description: "Long-running open tournament hosted by San Diego Badminton Club, paired with a Junior OLC."
  },

  // ---------------------------------------------------------------------
  // Independent / non-USAB tournaments, run by clubs or organizations on
  // their own (not part of the USA Badminton sanctioned circuit), found via
  // club websites and Facebook rather than usabadminton.org.
  // ---------------------------------------------------------------------
  {
    id: "cba-team-tournament-2026",
    name: "2026 CBA Team Tournament",
    level: "Independent Open Tournament",
    venue: "Capital Badminton Academy - Columbia",
    city: "Columbia",
    state: "MD",
    address: "9188 Red Branch Rd Suite 450, Columbia, MD 21045",
    lat: 39.2037,
    lng: -76.861,
    startDate: "2026-02-28",
    endDate: "2026-03-01",
    registrationDeadline: "2026-02-15T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: "Prizes TBD; $350 entry fee per team",
    sourcePlatform: "Club Website",
    sourceUrl: "https://www.capitalbadminton.com/tournaments",
    description: "Unranked, open, friendly team-format tournament run directly by Capital Badminton Academy (not USAB-sanctioned). Teams of 5 v 5 compete in ties of 5 matches each."
  },
  {
    id: "saab-lunar-new-year-open-2026",
    name: "2026 Lunar New Year Badminton Open Tournament",
    level: "Independent Open Tournament",
    venue: "Houston Badminton Center",
    city: "Stafford",
    state: "TX",
    address: "10550 West Airport Blvd, Stafford, TX 77477",
    lat: 29.6161,
    lng: -95.5577,
    startDate: "2026-03-27",
    endDate: "2026-03-29",
    registrationDeadline: "2026-03-20T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: 12000,
    prizeNote: "Over $12,000 in combined cash prizes and gifts across divisions",
    sourcePlatform: "Facebook",
    sourceUrl: "https://www.facebook.com/SAABHOU/",
    description: "Community open tournament organized by the Southern Asian Association of Badminton (SAAB), promoted on Facebook, with MD/WD/XD divisions across skill levels A-D plus youth U11/U13/U15. Registration via TournamentSoftware; entry fee $55-$150 depending on number of events. See southernbadminton.org for the brochure."
  },
  {
    id: "pioneer-badminton-open-fall-2026",
    name: "Fall 2026 Pioneer Badminton Open",
    level: "Independent Open Tournament",
    venue: "Pioneer Badminton",
    city: "Bolingbrook",
    state: "IL",
    address: "586 Territorial Dr, Bolingbrook, IL 60440",
    lat: 41.6829,
    lng: -88.1001,
    startDate: "2026-11-14",
    endDate: "2026-11-15",
    registrationDeadline: "2026-10-31T23:59:00",
    deadlineNote: "Registration and payment deadline; late entries after this incur a $10 fee until the Nov 7 drop/refund deadline",
    prizeMoney: null,
    prizeNote: "Prizes awarded to winners and runners-up of each flight (amount not listed)",
    sourcePlatform: "Facebook",
    sourceUrl: "https://www.facebook.com/events/1618962722292394/",
    description: "Individual-entry open (MS/MD/WS/WD/XD, ABCD drop-flight, 32-entry cap per event) run directly by Pioneer Badminton, found only via their Facebook event page. Not on TournamentSoftware or usabadminton.org. Fees $50/$70/$75 for 1/2/3 events via Zelle or Venmo; registration through a Google Form linked on the event page."
  },
  {
    id: "pioneer-team-tournament-fall-2026",
    name: "2026 Pioneer Team Tournament Fall",
    level: "Independent Open Tournament",
    venue: "Pioneer Badminton",
    city: "Bolingbrook",
    state: "IL",
    address: "586 Territorial Dr, Bolingbrook, IL 60440",
    lat: 41.6829,
    lng: -88.1001,
    startDate: "2026-12-05",
    endDate: "2026-12-06",
    registrationDeadline: "2026-11-21T23:59:00",
    deadlineNote: "Registration and payment deadline; drop/refund deadline is Nov 28",
    prizeMoney: null,
    prizeNote: "Cash prizes to 1st place and runner-up teams (amount not listed); $600 entry fee per team",
    sourcePlatform: "Facebook",
    sourceUrl: "https://www.facebook.com/events/1688524852458802/",
    description: "Team-format tournament (round robin into playoffs; each tie is 2MS/1WS/2MD/2WD/2XD, best of 9) run directly by Pioneer Badminton, found only via their Facebook event page. Minimum 4 teams to proceed. Fees $600/team via Zelle or Venmo; registration through a Google Form linked on the event page."
  },
  {
    id: "udel-intramural-badminton-2025",
    name: "University of Delaware Intramural Badminton Tournament",
    level: "College Club / Intramural",
    venue: "Carpenter Sports Building, Gym 2",
    city: "Newark",
    state: "DE",
    address: "Carpenter Sports Building, University of Delaware, Newark, DE 19711",
    lat: 39.6837,
    lng: -75.7497,
    startDate: "2025-11-02",
    endDate: "2025-11-02",
    registrationDeadline: "2025-10-30T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: "Recreational intramural event; no cash prize",
    sourcePlatform: "Club Website",
    sourceUrl: "https://www.imleagues.com/spa/sport/fc880ff855fd443e886caad7be9567b6/home",
    description: "Single-elimination intramural tournament (Co-Rec Doubles, Men's/Women's Doubles and Singles) open to University of Delaware students via IMLeagues. Runs each fall; check events.udel.edu for the current year's date."
  },
  {
    id: "msu-mankato-badminton-2026",
    name: "Asia Organization x Badminton Club Tournament",
    level: "College Club",
    venue: "Myers Field House",
    city: "Mankato",
    state: "MN",
    address: "Myers Field House, Minnesota State University, Mankato, MN",
    lat: 44.1636,
    lng: -93.9994,
    startDate: null,
    endDate: null,
    registrationDeadline: null,
    deadlineNote: "Held annually around late February; exact date not yet posted, check the club's Instagram",
    prizeMoney: null,
    prizeNote: "Small prizes for winners (club-funded)",
    sourcePlatform: "Instagram",
    sourceUrl: "https://www.msureporter.com/2026/02/26/asia-organization-and-badminton-club-bring-students-together-through-tournament/",
    description: "Student doubles-team tournament co-hosted by the Asia Organization and Minnesota State's Badminton Club, promoted mainly through Instagram, group chats, and campus flyers rather than any tournament platform."
  },

  // ---------------------------------------------------------------------
  // Additional tournaments pulled from TournamentSoftware's own national
  // search (tournamentsoftware.com/find, SportID=2/badminton, USA), rather
  // than from usabadminton.org's individual news posts. This is where most
  // club-hosted ranking tournaments and one-off opens actually live. Many
  // never get their own usabadminton.org announcement post at all.
  //
  // For entries where the search listing showed a live "Online Entry: X
  // days left" countdown, the registration deadline below was computed
  // from that countdown (captured 2026-09-07). For entries without that
  // countdown badge, registrationDeadline is left null. That does NOT
  // necessarily mean entry is closed, just that this page couldn't confirm
  // it; click through to check.
  // ---------------------------------------------------------------------
  {
    id: "ts-aeroplane-cba-open-2026",
    name: "2026 AEROPLANE Shuttlecock CBA Open",
    level: "Open Tournament",
    venue: "Capital Badminton Academy",
    city: "Columbia",
    state: "MD",
    address: "Capital Badminton Academy, Columbia, MD",
    lat: 39.2037,
    lng: -76.861,
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=93EF121A-C65A-4255-8049-C645B78262E5",
    entries: 316,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/D plus U13, Junior, and 40+ categories."
  },
  {
    id: "ts-charlotte-fall-challenge-juniors-2026",
    name: "2026 Charlotte Fall Challenge: Juniors",
    level: "Junior Tournament",
    venue: "Carolina Badminton Club",
    city: "Pineville",
    state: "NC",
    address: "Carolina Badminton Club, Pineville, NC",
    lat: 35.0855,
    lng: -80.8871,
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: "Junior event; no cash prize",
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=EFC4B21B-6A15-4617-84FF-D689027DC515",
    entries: 66,
    entriesUpdated: "2026-09-09",
    description: "U11/U13/U15 divisions. Restricted to Charlotte-area city kids per the listing."
  },
  {
    id: "ts-charlotte-badminton-open-2026",
    name: "2026 Charlotte Badminton Open",
    level: "Open Tournament",
    venue: "Carolina Badminton Club",
    city: "Pineville",
    state: "NC",
    address: "Carolina Badminton Club, Pineville, NC",
    lat: 35.0855,
    lng: -80.8871,
    startDate: "2026-09-12",
    endDate: "2026-09-13",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=D1546237-3B03-4D89-A583-3CDAA5951265",
    entries: 167,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C plus 40+."
  },
  {
    id: "ts-ebc-webadminton-charity-2026",
    name: "2026 EBC Webadminton Charity Tournament",
    level: "Charity Tournament",
    venue: "California Badminton",
    city: "Union City",
    state: "CA",
    address: "California Badminton, Union City, CA",
    lat: 37.5873,
    lng: -122.0216,
    startDate: "2026-09-12",
    endDate: "2026-09-13",
    registrationDeadline: "2026-09-08T23:59:00",
    deadlineNote: "Online entry closing very soon",
    prizeMoney: null,
    prizeNote: "Charity event",
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=A7C034D6-DD0E-47CF-A4B3-89B78DA3D237",
    entries: 266,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/D/J plus Open. Entry closes imminently, so register right away if interested."
  },
  {
    id: "ts-parker-tournament-2026",
    name: "Parker Tournament 2026",
    level: "Open Tournament",
    venue: "Parker Badminton Club",
    city: "Highlands Ranch",
    state: "CO",
    address: "Parker Badminton Club, Highlands Ranch, CO",
    lat: 39.5386,
    lng: -104.9726,
    startDate: "2026-09-13",
    endDate: "2026-09-13",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=0A4F35FC-033E-473A-8921-1540CE8844CD",
    entries: 130,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C plus U18."
  },
  {
    id: "ts-mbc-chicago-open-2026",
    name: "2026 Annual MBC Chicago Open",
    level: "Open Tournament",
    venue: "Midwest Badminton Club",
    city: "Darien",
    state: "IL",
    address: "8202 Lemont Road, Darien, IL 60516",
    lat: 41.7388,
    lng: -88.0122,
    startDate: "2026-09-18",
    endDate: "2026-09-20",
    registrationDeadline: "2026-09-06T23:59:00",
    deadlineNote: "11:59 PM CDT; entry has already closed (confirmed via tournament detail page)",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=A14003CC-070E-466A-A18E-AC5FCF4F3848",
    entries: 213,
    entriesUpdated: "2026-09-09",
    description: "9-and-under plus A/B/C divisions."
  },
  {
    id: "ts-fortius-junior-beginners-2026",
    name: "Fortius Junior Beginners Open 2026",
    level: "Junior Tournament (Beginners)",
    venue: "Fortius Sports Academy",
    city: "Cumming",
    state: "GA",
    address: "Fortius Sports Academy, Cumming, GA",
    lat: 34.2073,
    lng: -84.1402,
    startDate: "2026-09-19",
    endDate: "2026-09-19",
    registrationDeadline: "2026-09-18T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: "Junior beginners event; no cash prize",
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=0B48F2F4-EDE1-42D0-9E69-B7286F38DD20",
    entries: 25,
    entriesUpdated: "2026-09-09",
    description: "U9/U11/U13/U15/U17 beginner divisions."
  },
  {
    id: "ts-ccs-30th-charity-2026",
    name: "CCS 30th Anniversary Charity Tournament",
    level: "Charity Tournament",
    venue: "TS Badminton",
    city: "Norcross",
    state: "GA",
    address: "TS Badminton, Norcross, GA",
    lat: 33.9412,
    lng: -84.2135,
    startDate: "2026-09-20",
    endDate: "2026-09-20",
    registrationDeadline: "2026-09-13T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: "Charity event",
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=E0FF2CFA-6331-4D2A-B2D5-362B125647C2",
    entries: 45,
    entriesUpdated: "2026-09-09",
    description: "Open division plus U11/U15/U17."
  },
  {
    id: "ts-nvbc-open-championship-2026",
    name: "2026 NVBC Open Championship",
    level: "Open Tournament",
    venue: "Northern Virginia Badminton Club",
    city: "Ashburn",
    state: "VA",
    address: "Northern Virginia Badminton Club, Ashburn, VA",
    lat: 39.0298,
    lng: -77.4744,
    startDate: "2026-09-25",
    endDate: "2026-09-27",
    registrationDeadline: "2026-09-20T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=E2AB2ABA-191F-4772-9F79-40D9D2D390D1",
    entries: 40,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/D plus 35+/40+/50+."
  },
  {
    id: "ts-peak-open-2026",
    name: "Peak Open 2026",
    level: "Open Tournament",
    venue: "Peak Sport",
    city: "Morrisville",
    state: "NC",
    address: "Peak Sport, Morrisville, NC",
    lat: 35.8235,
    lng: -78.8256,
    startDate: "2026-09-25",
    endDate: "2026-09-27",
    registrationDeadline: "2026-09-11T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=378307EF-0AA1-48C9-81D0-5EC65B7E1022",
    entries: 102,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/J plus Junior U11/U13/U15 and Open. Same venue as December's national championships."
  },
  {
    id: "ts-northwest-open-2026",
    name: "Northwest Open 2026",
    level: "Open Tournament",
    venue: "Northwest Badminton Academy",
    city: "Snoqualmie",
    state: "WA",
    address: "Northwest Badminton Academy, Snoqualmie, WA",
    lat: 47.529,
    lng: -121.8271,
    startDate: "2026-09-26",
    endDate: "2026-09-27",
    registrationDeadline: "2026-09-13T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=80C90721-E2AF-46BE-9859-2EDCF3409240",
    entries: 90,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B plus U9-U17 and 30+/35+."
  },
  {
    id: "ts-fortius-south-olc-2026",
    name: "2026 Fortius South Open Local Championships",
    level: "Local Championship",
    venue: "USA Badminton",
    city: "Alpharetta",
    state: "GA",
    address: "Alpharetta, GA",
    lat: 34.0756,
    lng: -84.2946,
    startDate: "2026-10-02",
    endDate: "2026-10-04",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=75EE9BDC-5F76-4163-94BA-1A90582316FC",
    entries: 0,
    entriesUpdated: "2026-09-09",
    description: "USA Badminton sanctioned Open Local Championship; U11/U13/U15/U17/U19 divisions."
  },
  {
    id: "ts-golden-bear-lxxii-2026",
    name: "2026 Golden Bear LXXII",
    level: "Open Tournament",
    venue: "California Badminton",
    city: "San Francisco",
    state: "CA",
    address: "California Badminton, San Francisco, CA",
    lat: 37.7879,
    lng: -122.4075,
    startDate: "2026-10-03",
    endDate: "2026-10-04",
    registrationDeadline: "2026-09-28T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=7EEDD506-53C6-47E0-8E06-31B2D589CFDF",
    entries: 44,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/D. \"LXXII\" marks the tournament's 72nd annual running."
  },
  {
    id: "ts-ibc-indy-open-2026",
    name: "2026 IBC Indy Open",
    level: "Open Tournament",
    venue: "Indy Badminton Club",
    city: "Carmel",
    state: "IN",
    address: "Indy Badminton Club, Carmel, IN",
    lat: 39.9784,
    lng: -86.1284,
    startDate: "2026-10-03",
    endDate: "2026-10-04",
    registrationDeadline: "2026-09-13T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=02CCA815-2496-4997-AC0E-8F3B8FD47A4D",
    entries: 47,
    entriesUpdated: "2026-09-09",
    description: null
  },
  {
    id: "ts-arise-international-challenge-2026",
    name: "Arise International Challenge 2026",
    level: "International Challenge (BWF)",
    venue: "Badminton Pan Am",
    city: "Brookshire",
    state: "TX",
    address: "Brookshire, TX",
    lat: 29.7861,
    lng: -95.9511,
    startDate: "2026-10-07",
    endDate: "2026-10-11",
    registrationDeadline: "2026-09-08T10:00:00",
    deadlineNote: "Online entry closing within hours as of when this was added; likely a local wildcard window, since the main international entry deadline has probably already passed",
    prizeMoney: null,
    prizeNote: "BWF International Challenge events carry a BWF-mandated prize fund; check the official page for the exact amount",
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=06A76B83-EBF7-4AD8-8A34-2D621ED4978C",
    description: "BWF-sanctioned International Challenge run by Badminton Pan Am; entry via BWF's system rather than direct TournamentSoftware entry."
  },
  {
    id: "ts-massbad-northeast-orc-2026",
    name: "2026 YONEX MASSBAD Northeast Open Regional Championships",
    level: "Regional Championship",
    venue: "USA Badminton",
    city: "Harvard",
    state: "MA",
    address: "Harvard, MA",
    lat: 42.3657,
    lng: -71.1222,
    startDate: "2026-10-10",
    endDate: "2026-10-12",
    registrationDeadline: "2026-09-16T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=A5A277E2-E158-4BAA-B1F5-6BA4B8F99014",
    entries: 206,
    entriesUpdated: "2026-09-09",
    description: "USA Badminton sanctioned Open Regional Championship for the Northeast region; U11/U13/U15/U17/U19 divisions."
  },
  {
    id: "ts-hbdf-hana-challenge-2026",
    name: "HBDF Hana Challenge 2026",
    level: "Open Tournament",
    venue: "SCBA",
    city: "Santa Fe Springs",
    state: "CA",
    address: "SCBA, Santa Fe Springs, CA",
    lat: 33.9481,
    lng: -118.0691,
    startDate: "2026-10-17",
    endDate: "2026-10-17",
    registrationDeadline: "2026-10-10T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=F5DF78FA-2078-4BB0-86AF-AAE8DB4B2233",
    entries: 5,
    entriesUpdated: "2026-09-09",
    description: "Open plus U11/U14 and 45+. Entry handled via a separate rating-system platform rather than direct TournamentSoftware entry."
  },
  {
    id: "ts-cardinal-open-2026",
    name: "2026 Cardinal Open",
    level: "Open Tournament",
    venue: "California Badminton",
    city: "Union City",
    state: "CA",
    address: "California Badminton, Union City, CA",
    lat: 37.5873,
    lng: -122.0216,
    startDate: "2026-10-17",
    endDate: "2026-10-18",
    registrationDeadline: "2026-10-11T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=37133CCA-6DD6-484F-B874-D19B51C03B4C",
    entries: 7,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/D/J."
  },
  {
    id: "ts-ncbc-fall-open-2026",
    name: "2026 NCBC Fall Open",
    level: "Open Tournament",
    venue: "NorCal Badminton Center",
    city: "Rancho Cordova",
    state: "CA",
    address: "NorCal Badminton Center, Rancho Cordova, CA",
    lat: 38.5891,
    lng: -121.3027,
    startDate: "2026-10-17",
    endDate: "2026-10-18",
    registrationDeadline: "2026-10-11T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=1BA611C7-5BB9-4FEF-978E-7E1F86C286A6",
    entries: 24,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/D/J plus U11/U16."
  },
  {
    id: "ts-austin-leander-south-olc-2026",
    name: "2026 Austin Leander South Open Local Championships",
    level: "Local Championship",
    venue: "USA Badminton",
    city: "Leander",
    state: "TX",
    address: "Leander, TX",
    lat: 30.5788,
    lng: -97.8531,
    startDate: "2026-10-23",
    endDate: "2026-10-25",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=2361B522-B57A-4397-8E4D-DD58F2AF49F7",
    entries: 0,
    entriesUpdated: "2026-09-09",
    description: "USA Badminton sanctioned Open Local Championship; U11/U13/U15/U17/U19 divisions."
  },
  {
    id: "ts-sonic-smash-2026",
    name: "Sonic Smash 2026",
    level: "Open Tournament",
    venue: "A Little More Support",
    city: "Tukwila",
    state: "WA",
    address: "Tukwila, WA",
    lat: 47.4779,
    lng: -122.261,
    startDate: "2026-10-23",
    endDate: "2026-10-25",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=A358C5A2-04CA-4861-8ABC-C7D3C569634B",
    entries: 0,
    entriesUpdated: "2026-09-09",
    description: null
  },
  {
    id: "ts-pbca-oktoberfest-2026",
    name: "2026 PBCA Oktoberfest",
    level: "Open Tournament (21+)",
    venue: "Philippine Badminton Club of America",
    city: "El Monte",
    state: "CA",
    address: "Philippine Badminton Club of America, El Monte, CA",
    lat: 34.0752,
    lng: -118.0368,
    startDate: "2026-10-24",
    endDate: "2026-10-24",
    registrationDeadline: "2026-09-26T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=1C896952-0D7A-4862-BF91-07A7025FF291",
    entries: 4,
    entriesUpdated: "2026-09-09",
    description: "21-and-over division. Entry handled via a separate rating-system platform rather than direct TournamentSoftware entry."
  },
  {
    id: "ts-madison-badminton-invitational-2026",
    name: "Madison Badminton Invitational 2026",
    level: "Invitational",
    venue: "Glacier Creek Middle School",
    city: "Cross Plains",
    state: "WI",
    address: "2314 Apple Wood Dr, Cross Plains, WI 53528",
    lat: 43.1133,
    lng: -89.6366,
    startDate: "2026-10-24",
    endDate: "2026-10-24",
    registrationDeadline: "2026-10-09T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=378084DD-90F9-4449-A9A6-AEAB6611703D",
    entries: 5,
    entriesUpdated: "2026-09-09",
    description: "Open Mens/Womens/Mixed Doubles, Funky Doubles (combined age 70+), Family/Junior Doubles, and Junior Singles. Junior (U16) fees waived thanks to sponsors. Also listed on Facebook (facebook.com/events/1538432384977567)."
  },
  {
    id: "ts-bintang-norcal-orc-2026",
    name: "2026 YONEX Bintang NorCal Open Regional Championships",
    level: "Regional Championship",
    venue: "USA Badminton",
    city: "Fremont",
    state: "CA",
    address: "Fremont, CA",
    lat: 37.5485,
    lng: -121.9886,
    startDate: "2026-11-07",
    endDate: "2026-11-09",
    registrationDeadline: "2026-10-07T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=879C8DEC-B8E8-4AB4-8841-7D07D34950CF",
    entries: 77,
    entriesUpdated: "2026-09-09",
    description: "USA Badminton sanctioned Open Regional Championship; U11/U13/U15/U17/U19 divisions. Distinct from the earlier Bintang NorCal Open Local Championship in March."
  },
  {
    id: "ts-boba-solo-2026",
    name: "Boba Solo 2026: Singles Tournament",
    level: "Singles Tournament",
    venue: "Bobaminton",
    city: "Tukwila",
    state: "WA",
    address: "Tukwila, WA",
    lat: 47.4779,
    lng: -122.261,
    startDate: "2026-11-14",
    endDate: "2026-11-14",
    registrationDeadline: "2026-10-24T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=FC738607-2326-4D72-B704-C9B47BA2B7B4",
    entries: 7,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/D/J, singles-only format."
  },
  {
    id: "ts-cba-open-2026-nov",
    name: "CBA Open 2026",
    level: "Open Tournament",
    venue: "Chicago Badminton Academy",
    city: "Chicago",
    state: "IL",
    address: "Chicago Badminton Academy, Chicago, IL",
    lat: 41.8781,
    lng: -87.6298,
    startDate: "2026-11-14",
    endDate: "2026-11-15",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=786BDF3A-236F-402A-A065-D6C3370E7F6D",
    entries: 0,
    entriesUpdated: "2026-09-09",
    description: "Open plus U11 and 40+."
  },
  {
    id: "ts-topshot-open-2026",
    name: "TopShot Open",
    level: "Open Tournament",
    venue: "TopShot LLC",
    city: "Cedar Park",
    state: "TX",
    address: "840 N. Vista Ridge Blvd, Cedar Park, TX 78613",
    lat: 30.5297,
    lng: -97.7908,
    startDate: "2026-11-14",
    endDate: "2026-11-15",
    registrationDeadline: "2026-11-07T23:59:00",
    deadlineNote: "11:59 PM CST",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=BFA24072-D511-4628-B54E-9FC5A0DD660E",
    entries: 0,
    entriesUpdated: "2026-09-09",
    description: "Open plus U11/U13/U15/U17 and 35+/45+/55+. Near Austin, TX."
  },
  {
    id: "ts-mid-atlantic-badminton-2026",
    name: "2026 Mid-Atlantic Badminton Tournament",
    level: "Masters/Senior Tournament",
    venue: "Midwest Senior Badminton",
    city: "Columbia",
    state: "MD",
    address: "Columbia, MD",
    lat: 39.2037,
    lng: -76.861,
    startDate: "2026-11-20",
    endDate: "2026-11-22",
    registrationDeadline: "2026-11-08T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=64923D76-00A1-457A-B87D-602D831E8352",
    entries: 3,
    entriesUpdated: "2026-09-09",
    description: "Senior/masters divisions only: 34+, 39+, 44+, 49+, 54+, 59+, 64+."
  },
  {
    id: "ts-fortius-atlanta-open-2026",
    name: "Fortius Atlanta Badminton Open 2026",
    level: "Open Tournament",
    venue: "Fortius Sports Academy",
    city: "Alpharetta",
    state: "GA",
    address: "Fortius Sports Academy, Alpharetta, GA",
    lat: 34.0756,
    lng: -84.2946,
    startDate: "2026-11-20",
    endDate: "2026-11-22",
    registrationDeadline: "2026-11-06T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=5AA6988A-3A7F-455D-8945-0627A41B7F82",
    entries: 4,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/17+/C plus Open, U11/U13/U15/U16/U17, and 40+/45+."
  },
  {
    id: "ts-cba-midwest-olc-2026-nov",
    name: "2026 CBA Midwest Open Local Championships (November)",
    level: "Local Championship",
    venue: "USA Badminton",
    city: "Chicago",
    state: "IL",
    address: "Chicago, IL",
    lat: 41.8781,
    lng: -87.6298,
    startDate: "2026-11-21",
    endDate: "2026-11-22",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=B8AA03C7-DEAF-4703-BB26-38B5845E9DA1",
    entries: 0,
    entriesUpdated: "2026-09-09",
    description: "USA Badminton sanctioned Open Local Championship; U11/U13/U15/U17/U19 divisions. A separate Midwest OLC was already held in January."
  },
  {
    id: "ts-socal-closed-orc-2026",
    name: "2026 SoCal Closed Regional Championships",
    level: "Regional Championship (Closed)",
    venue: "USA Badminton",
    city: "El Monte",
    state: "CA",
    address: "El Monte, CA",
    lat: 34.0752,
    lng: -118.0368,
    startDate: "2026-11-21",
    endDate: "2026-11-22",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=13C25A98-AD65-43A9-ABF3-C80D6FB210C5",
    entries: 0,
    entriesUpdated: "2026-09-09",
    description: "\"Closed\" championship (entry restricted, e.g. by residency/club) rather than an open regional; U11/U13/U15/U17/U19 divisions."
  },
  {
    id: "ts-bay-badminton-championships-2026",
    name: "2026 Bay Badminton Championships",
    level: "Open Tournament",
    venue: "F & K Tournaments",
    city: "Milpitas",
    state: "CA",
    address: "Milpitas, CA",
    lat: 37.4332,
    lng: -121.8989,
    startDate: "2026-11-27",
    endDate: "2026-11-29",
    registrationDeadline: null,
    deadlineNote: "Not shown as open for online entry, so check the tournament page",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=1EB36537-8088-4C57-87B2-6DB1B834C292",
    entries: 5,
    entriesUpdated: "2026-09-09",
    description: "Open divisions A/B/C/D/J plus 39+."
  },
  {
    id: "ts-la-open-2026",
    name: "LA Open 2026",
    level: "International Series (BWF)",
    venue: "Badminton Pan Am",
    city: "Los Angeles",
    state: "CA",
    address: "Los Angeles, CA",
    lat: 34.0537,
    lng: -118.2428,
    startDate: "2026-12-08",
    endDate: "2026-12-13",
    registrationDeadline: "2026-11-09T23:59:00",
    deadlineNote: "11:59 PM",
    prizeMoney: null,
    prizeNote: "BWF International Series events carry a BWF-mandated prize fund; check the official page for the exact amount",
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=FFE5309D-C69D-4D3F-AB11-7A74D1B7F456",
    description: "BWF-sanctioned International Series run by Badminton Pan Am; entry via BWF's system rather than direct TournamentSoftware entry."
  },

  // ---------------------------------------------------------------------
  // LEAGUES, pulled from TournamentSoftware's own league search
  // (tournamentsoftware.com/find/league, SportID=2/badminton, USA). This is
  // the complete result set for that search at the time this was built
  // (3 leagues). Re-run the search periodically for new ones; see README.md.
  // ---------------------------------------------------------------------
  {
    id: "ts-league-og-flash-team-war-2026",
    name: "OG Flash Team War",
    activityType: "league",
    level: "Team League: Flash Doubles",
    venue: "Fortius Sports Academy",
    city: "Alpharetta",
    state: "GA",
    address: "Fortius Sports Academy, Alpharetta, GA",
    lat: 34.0756,
    lng: -84.2946,
    startDate: "2026-09-12",
    endDate: "2026-09-12",
    registrationDeadline: "2026-08-29T23:59:00",
    deadlineNote: "11:59 PM (entry window was Aug 26 to 29)",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=61067EDA-16FB-4CFE-9CA1-D73629CA88EE",
    description: "One-day team-format \"Flash Doubles\" league event hosted by Fortius Sports Academy."
  },
  {
    id: "ts-league-fortius-international-team-2026",
    name: "Fortius International Team League",
    activityType: "league",
    level: "Team League",
    venue: "Fortius Sports Academy",
    city: "Alpharetta",
    state: "GA",
    address: "5905 Ronald Reagan Blvd, Alpharetta, GA 30005",
    lat: 34.0756,
    lng: -84.2946,
    startDate: "2026-10-10",
    endDate: "2026-11-08",
    registrationDeadline: null,
    deadlineNote: "No online-entry deadline listed; contact the venue (see league page) to join",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=41F7F0C9-D0DB-4346-B59A-D759BA9228F7",
    description: "Weekend team-league matches over 5 weekends (Sat/Sun) from Oct 10 through Nov 8, 2026, hosted by Fortius Sports Academy."
  },
  {
    id: "ts-league-norcal-collegiate-teams-2026",
    name: "NorCal Collegiate Teams Championships",
    activityType: "league",
    level: "Collegiate Team League",
    venue: "Northeast Badminton Association",
    city: "Union City",
    state: "CA",
    address: "Union City, CA",
    lat: 37.5873,
    lng: -122.0216,
    startDate: "2026-11-07",
    endDate: "2026-11-08",
    registrationDeadline: "2026-10-24T23:59:00",
    deadlineNote: "11:59 PM PT; team and player nominations both close this date",
    prizeMoney: null,
    prizeNote: null,
    sourcePlatform: "TournamentSoftware",
    sourceUrl: "https://www.tournamentsoftware.com/sport/tournament?id=F3E40EC8-1D5A-4845-9CC9-71060AA49838",
    description: "Collegiate team-league championship weekend, organized by the Northeast Badminton Association despite the NorCal name and California venue. Part of the same organization's National Collegiate Team Badminton structure (which also runs Division 1A/1B/2/3 playoffs elsewhere in the season)."
  },

  // ---------------------------------------------------------------------
  // Found via a manual sweep of 38 university badminton club Instagram
  // accounts (see badminton instagrams.txt), reading each account's visible
  // post grid without logging in. Instagram's own alt-text image
  // descriptions (which include OCR'd flyer text) were used to read post
  // content. This was the ONLY genuine open-tournament announcement found
  // across all 38 accounts as of 2026-09-07; every other club's recent
  // posts were internal tryouts, practice schedules, recruitment/quad-day
  // events, or socials, not tournaments anyone outside the club could enter.
  // Re-sweep periodically; a club's own open tournament is a rare post for
  // most of these accounts.
  // ---------------------------------------------------------------------
  {
    id: "ig-cmu-open-tournament-2026",
    name: "2026 CMU Open Tournament",
    level: "Open Tournament",
    venue: "Carnegie Mellon University (Highmark & Wiegand Gymnasiums)",
    city: "Pittsburgh",
    state: "PA",
    address: "Carnegie Mellon University, Pittsburgh, PA",
    lat: 40.4443,
    lng: -79.9436,
    startDate: "2026-09-19",
    endDate: "2026-09-20",
    registrationDeadline: null,
    deadlineNote: "Early-bird pricing ended before Sept 1; the regular/final entry deadline wasn't shown in the post, so check the Instagram link",
    prizeMoney: null,
    prizeNote: "Cash prizes available (amount not specified in the announcement)",
    sourcePlatform: "Instagram",
    sourceUrl: "https://www.instagram.com/cmubadminton/p/Dbb9Hbxpyeh/",
    description: "Open badminton tournament hosted by Carnegie Mellon University's Club Badminton team: MS/WS/MD/WD/XD divisions, elimination bracket. Announced only on the club's Instagram (@cmubadminton); not listed on TournamentSoftware or usabadminton.org."
  }
];
